Init1
Modris-lat/Scooter-Rental pull request #1
Opened 2020-09-22 10:23 UTC by Modris-lat

2020-09-24 08:13 UTC, EdgarsSalmins commented on ScooterRental/Company.cs
> +    public class Company: IScooterService, IRentalCompany
Company implementē tikai IRentalCompany interfeisu. :) 
IScooterService interfeisu implementēt vajadzētu citai klasei.

2020-09-24 08:14 UTC, EdgarsSalmins commented on ScooterRental.Tests/CompanyTest.cs
> +        public CompanyTest()
Testi jāraksta pret interfeisu ne klasi. :)

2020-09-24 08:14 UTC, EdgarsSalmins commented on ScooterRental.Tests/CompanyTest.cs
> +            Assert.ThrowsException<ArgumentException>(() => company.AddScooter("01", 0.50m));
Jātaisa custom exception. t.i. existējošie microsofta neder.

2020-09-24 08:20 UTC, EdgarsSalmins commented on ScooterRental/Company.cs
> +        {
nav pārbaudes uz negatīvu minūtes cenu.

2020-09-24 08:22 UTC, EdgarsSalmins requested changes
ir daži komentāri... 
Tos jāsalabo.. tad skatīšos sīkāk.
.vs mape jāizņem ārā.

2020-10-07 12:56 UTC, EdgarsSalmins commented on ScooterRental/Exceptions/EndRentException.cs
> +        public EndRentException(): base("Scooter by this ID is not rented or wrong ID!") {}
Scooter Not Rented Exception? 
un ja wrong Id es teiktu ka tas jau būtu cits exception ja tāds case vispār ir.

2020-10-07 13:00 UTC, EdgarsSalmins commented on ScooterRental/RentalCompany.cs
> +            if (RentedScooters.ShowRentedScooters().Count > 0)
var rentedScooters = RentedCooters.ShowRentedScooters() ? 
un tad rentedScooters.Any() ? 
un tālāk strādā ar mainīgo? kur jau tev ir tie scooteri?

2020-10-07 13:01 UTC, EdgarsSalmins commented on ScooterRental/RentalCompany.cs
> +                        {
saturs iekš if ne ar ko neatšķiras no nākošā ifa. 
varbūt ir vērts iznest atsevišķā metodē?

2020-10-07 13:04 UTC, EdgarsSalmins commented on ScooterRental/RentalCompany.cs
> +            foreach (var rScooter in RentedScooters.ShowRentedScooters())
negribēji singleOrDefault(a => a.id == id) ? 
daudz īsāks kods būtu. :)
vieglāk uztvert.

2020-10-07 13:04 UTC, EdgarsSalmins commented on ScooterRental/RentalCompany.cs
> +                if (scooter.Id == id)
if atkārtojās.. negribēji aizstāt ar kādu GetById metodi?

2020-10-07 13:08 UTC, EdgarsSalmins commented on ScooterRental/RentalService.cs
> +            foreach (Scooter scooter in AllScooters)
var aizstāt foreach ar any(id == id)
nebūtu jāskraida ciklā cauri.

2020-10-07 13:08 UTC, EdgarsSalmins commented on ScooterRental/RentalService.cs
> +            foreach (Scooter s in AllScooters)
singleOrDefault ?

2020-10-07 13:09 UTC, EdgarsSalmins commented on ScooterRental/RentalService.cs
> +            foreach (Scooter scooter in AllScooters)
return allScooters.Where(notRented).ToList()?

2020-10-07 13:14 UTC, EdgarsSalmins commented on ScooterRental/RentedScooterList.cs
> +            foreach (RentedScooter scooter in RentedScooters)
getById ?

2020-10-07 13:15 UTC, EdgarsSalmins commented on ScooterRental/RentedScooterList.cs
> +            foreach (RentedScooter scooter in RentedScooters)
vai vēl labāk pat pārbaudīt vai existē atsevišķā metodē? viscauri kodam to dari.

2020-10-07 13:16 UTC, EdgarsSalmins commented on ScooterRental/RentedScooterList.cs
> +            bool exists = false;
priekš kam šito mainīgo izmanto?

2020-10-07 13:20 UTC, Modris-lat commented on ScooterRental/RentalCompany.cs
> +            foreach (var rScooter in RentedScooters.ShowRentedScooters())
es sapratu, ka loops ir ātrāks par linq, tādēļ vairāk uz for loopiem iespringstu un arī saprotamāk itkā, vai es kļūdos?

2020-10-07 13:25 UTC, Modris-lat commented on ScooterRental/RentedScooterList.cs
> +            foreach (RentedScooter scooter in RentedScooters)
getscooterById met exception, ja scooteris neeksistē, šeit exceptions īsti laikam nav vajadzīgs.

2020-10-09 07:27 UTC, EdgarsSalmins commented on ScooterRental/RentalCompany.cs
> +            foreach (var rScooter in RentedScooters.ShowRentedScooters())
https://stackoverflow.com/questions/14893924/for-vs-linq-performance-vs-future
https://stackoverflow.com/questions/3156059/is-a-linq-statement-faster-than-a-foreach-loop/3156074

divi linki par performance uz linq un loops.. :) loops ir ātrāks.. :) un atkarīgs no ierakstu skaita. 
bet tur vienmēr ir duelis starp uzturamību un performanci.

2020-10-09 07:27 UTC, EdgarsSalmins requested changes
neko jaunu vairs neieraudzīju. :) 
mēģini safiksot šito.

2020-10-11 08:48 UTC, Modris-lat commented on ScooterRental/Exceptions/EndRentException.cs
> +        public EndRentException(): base("Scooter by this ID is not rented or wrong ID!") {}
izlabots

2020-10-11 10:12 UTC, Modris-lat commented on ScooterRental/RentalCompany.cs
> +            if (RentedScooters.ShowRentedScooters().Count > 0)
Paldies! Izlaboju. Vēl citās metodēs arī nedaudz vienkāršoju.

2020-10-11 10:16 UTC, Modris-lat commented on ScooterRental/RentalCompany.cs
> +                        {
uztaisīju StartAndEndRents metodi, tagad viena rindiņa.

2020-10-11 10:26 UTC, Modris-lat commented on ScooterRental/RentalCompany.cs
> +            foreach (var rScooter in RentedScooters.ShowRentedScooters())
nu jā, tur pat saka, ka linq ir ātrāks par foreach, ko es izmantoju. Principā laikam jāspiež uz linq. Vienkārši visu laiku kodēts ar parastajiem loopiem, jau pieradums.

2020-10-11 10:37 UTC, Modris-lat commented on ScooterRental/RentalCompany.cs
> +                if (scooter.Id == id)
no getById nāk exception, tur tādu exception nevajag

2020-10-11 10:41 UTC, Modris-lat commented on ScooterRental/RentalService.cs
> +            foreach (Scooter scooter in AllScooters)
izlabots

2020-10-11 10:44 UTC, Modris-lat commented on ScooterRental/RentalService.cs
> +            foreach (Scooter s in AllScooters)
izlabots

2020-10-11 10:47 UTC, Modris-lat commented on ScooterRental/RentalService.cs
> +            foreach (Scooter scooter in AllScooters)
izlabots

2020-10-11 11:07 UTC, Modris-lat commented on ScooterRental/RentedScooterList.cs
> +            bool exists = false;
saliku visur Linq un nodzēsu šo.

2020-10-14 13:57 UTC, EdgarsSalmins approved these changes

2020-10-14 14:00 UTC, merged